// charData.js
const characters = [
  {
    id: 1,
    image: "/char-imgs/card_baizhi.webp",
    name: "Baizhi",
    elementType: "/element-icons/glacio.png",
    roles: "Support",
    rarity: 4,
    weapon: "Rectifier",
    elementTypeName: "Glacio",
  },
  {
    id: 2,
    image: "/char-imgs/card_jiyan.webp",
    name: "Jiyan",
    elementType: "/element-icons/aero.png",
    roles: "DPS",
    rarity: 5,
    weapon: "Broadblade",
    elementTypeName: "Aero",
  },
  {
    id: 3,
    image: "/char-imgs/card_yinlin.webp",
    name: "Yinlin",
    elementType: "/element-icons/electro.png",
    roles: "Sub-DPS",
    rarity: 5,
    weapon: "Rectifier",
    elementTypeName: "Electro",
  },
  {
    id: 4,
    image: "/char-imgs/card_aalto.webp",
    name: "Aalto",
    elementType: "/element-icons/aero.png",
    roles: "Sub-DPS",
    rarity: 4,
    weapon: "Pistol",
    elementTypeName: "Aero",
  },
  {
    id: 5,
    image: "/char-imgs/card_carlotta.webp",
    name: "Carlotta",
    elementType: "/element-icons/glacio.png",
    roles: "DPS",
    rarity: 5,
    weapon: "Pistol",
    elementTypeName: "Glacio",
  },
  {
    id: 6,
    image: "/char-imgs/card_chixia.webp",
    name: "Chixia",
    elementType: "/element-icons/fusion.png",
    roles: "DPS",
    rarity: 4,
    weapon: "Pistol",
    elementTypeName: "Fusion",
  },
  {
    id: 7,
    image: "/char-imgs/card_mortefi.webp",
    name: "Mortefi",
    elementType: "/element-icons/fusion.png",
    roles: "Sub-DPS, Support",
    rarity: 4,
    weapon: "Pistol",
    elementTypeName: "Fusion",
  },
  {
    id: 8,
    image: "/char-imgs/card_ciaccona.webp",
    name: "Ciaccona",
    elementType: "/element-icons/aero.png",
    roles: "Support",
    rarity: 5,
    weapon: "Pistol",
    elementTypeName: "Aero",
  },
  {
    id: 9,
    image: "/char-imgs/card_cantarella.webp",
    name: "Cantarella",
    elementType: "/element-icons/havoc.png",
    roles: "Support, Sub-DPS",
    rarity: 5,
    weapon: "Rectifier",
    elementTypeName: "Havoc",
  },
  {
    id: 10,
    image: "/char-imgs/card_encore.webp",
    name: "Encore",
    elementType: "/element-icons/fusion.png",
    roles: "Sub-DPS, DPS",
    rarity: 5,
    weapon: "Rectifier",
    elementTypeName: "Fusion",
  },
  {
    id: 11,
    image: "/char-imgs/card_phoebe.webp",
    name: "Phoebe",
    elementType: "/element-icons/spectro.png",
    roles: "Sub-DPS, DPS",
    rarity: 5,
    weapon: "Rectifier",
    elementTypeName: "Spectro",
  },
  {
    id: 12,
    image: "/char-imgs/card_shorekeeper.webp",
    name: "The Shorekeeper",
    elementType: "/element-icons/spectro.png",
    roles: "Support",
    rarity: 5,
    weapon: "Rectifier",
    elementTypeName: "Spectro",
  },
  {
    id: 13,
    image: "/char-imgs/card_verina.webp",
    name: "Verina",
    elementType: "/element-icons/spectro.png",
    roles: "Support",
    rarity: 5,
    weapon: "Rectifier",
    elementTypeName: "Spectro",
  },
  {
    id: 14,
    image: "/char-imgs/card_zhezhi.webp",
    name: "Zhezhi",
    elementType: "/element-icons/glacio.png",
    roles: "Support, Sub-DPS",
    rarity: 5,
    weapon: "Rectifier",
    elementTypeName: "Glacio",
  },
  {
    id: 15,
    image: "/char-imgs/card_brant.webp",
    name: "Brant",
    elementType: "/element-icons/fusion.png",
    roles: "Support, Sub-DPS",
    rarity: 5,
    weapon: "Sword",
    elementTypeName: "Fusion",
  },
  {
    id: 16,
    image: "/char-imgs/card_camellya.webp",
    name: "Camellya",
    elementType: "/element-icons/havoc.png",
    roles: "DPS, Sub-DPS",
    rarity: 5,
    weapon: "Sword",
    elementTypeName: "Havoc",
  },
  {
    id: 17,
    image: "/char-imgs/card_changli.webp",
    name: "Changli",
    elementType: "/element-icons/fusion.png",
    roles: "DPS, Sub-DPS",
    rarity: 5,
    weapon: "Sword",
    elementTypeName: "Fusion",
  },
  {
    id: 18,
    image: "/char-imgs/card_danjin.webp",
    name: "Danjin",
    elementType: "/element-icons/havoc.png",
    roles: "DPS, Sub-DPS",
    rarity: 4,
    weapon: "Sword",
    elementTypeName: "Havoc",
  },
  {
    id: 19,
    image: "/char-imgs/rover_card_spectro.webp",
    name: "Rover",
    elementType: "/element-icons/spectro.png",
    roles: "DPS, Sub-DPS",
    rarity: 5,
    weapon: "Sword",
    elementTypeName: "Spectro",
  },
  {
    id: 20,
    image: "/char-imgs/rover_card_havoc.webp",
    name: "Rover",
    elementType: "/element-icons/havoc.png",
    roles: "DPS, Sub-DPS",
    rarity: 5,
    weapon: "Sword",
    elementTypeName: "Havoc",
  },
  {
    id: 21,
    image: "/char-imgs/rover_card_aero.webp",
    name: "Rover",
    elementType: "/element-icons/aero.png",
    roles: "DPS, Sub-DPS",
    rarity: 5,
    weapon: "Sword",
    elementTypeName: "Aero",
  },
  {
    id: 22,
    image: "/char-imgs/card_sanhua.webp",
    name: "Sanhua",
    elementType: "/element-icons/glacio.png",
    roles: "Sub-DPS",
    rarity: 4,
    weapon: "Sword",
    elementTypeName: "Glacio",
  },
  {
    id: 23,
    image: "/char-imgs/card_yangyang.webp",
    name: "Yangyang",
    elementType: "/element-icons/aero.png",
    roles: "Sub-DPS",
    rarity: 4,
    weapon: "Sword",
    elementTypeName: "Aero",
  },
  {
    id: 24,
    image: "/char-imgs/card_jianxin.webp",
    name: "Jianxin",
    elementType: "/element-icons/aero.png",
    roles: "Sub-DPS",
    rarity: 5,
    weapon: "Gauntlet",
    elementTypeName: "Aero",
  },
  {
    id: 25,
    image: "/char-imgs/card_lingyang.webp",
    name: "Lingyang",
    elementType: "/element-icons/glacio.png",
    roles: "DPS, Sub-DPS",
    rarity: 5,
    weapon: "Gauntlet",
    elementTypeName: "Glacio",
  },
  {
    id: 26,
    image: "/char-imgs/card_roccia.webp",
    name: "Roccia",
    elementType: "/element-icons/havoc.png",
    roles: "Sub-DPS",
    rarity: 5,
    weapon: "Gauntlet",
    elementTypeName: "Havoc",
  },
  {
    id: 27,
    image: "/char-imgs/card_xiang.webp",
    name: "Xiangli Yao",
    elementType: "/element-icons/electro.png",
    roles: "DPS, Sub-DPS",
    rarity: 5,
    weapon: "Gauntlet",
    elementTypeName: "Electro",
  },
  {
    id: 28,
    image: "/char-imgs/card_youhu.webp",
    name: "Youhu",
    elementType: "/element-icons/glacio.png",
    roles: "Support",
    rarity: 4,
    weapon: "Gauntlet",
    elementTypeName: "Glacio",
  },
  {
    id: 29,
    image: "/char-imgs/card_yuanwu.webp",
    name: "Yuanwu",
    elementType: "/element-icons/electro.png",
    roles: "Sub-DPS, Support",
    rarity: 4,
    weapon: "Gauntlet",
    elementTypeName: "Electro",
  },
  {
    id: 30,
    image: "/char-imgs/card_zani.webp",
    name: "Zani",
    elementType: "/element-icons/spectro.png",
    roles: "Sub-DPS, Support",
    rarity: 5,
    weapon: "Gauntlet",
    elementTypeName: "Spectro",
  },
  {
    id: 31,
    image: "/char-imgs/card_calcharo.webp",
    name: "Calcharo",
    elementType: "/element-icons/electro.png",
    roles: "DPS, Sub-DPS",
    rarity: 5,
    weapon: "Broadblade",
    elementTypeName: "Electro",
  },
  {
    id: 32,
    image: "/char-imgs/card_jinhsi.webp",
    name: "Jinhsi",
    elementType: "/element-icons/spectro.png",
    roles: "DPS, Sub-DPS",
    rarity: 5,
    weapon: "Broadblade",
    elementTypeName: "Spectro",
  },
  {
    id: 33,
    image: "/char-imgs/card_lumi.webp",
    name: "Lumi",
    elementType: "/element-icons/electro.png",
    roles: "Sub-DPS",
    rarity: 4,
    weapon: "Broadblade",
    elementTypeName: "Electro",
  },
  {
    id: 34,
    image: "/char-imgs/card_taoqi.webp",
    name: "Taoqi",
    elementType: "/element-icons/havoc.png",
    roles: "Sub-DPS, Support",
    rarity: 4,
    weapon: "Broadblade",
    elementTypeName: "Havoc",
  },
];

export default characters;
